# Copyright (c) ModelScope Contributors. All rights reserved.
from .model import (
    AddAdapterRequest,
    AddMetricRequest,
    AddMetricResponse,
    AdapterRequest,
    ApplyPatchRequest,
    ApplyPatchResponse,
    BackwardResponse,
    CalculateLossResponse,
    CalculateMetricRequest,
    CalculateMetricResponse,
    ClipGradAndStepRequest,
    ClipGradAndStepResponse,
    ClipGradNormRequest,
    ClipGradNormResponse,
    CreateRequest,
    CreateResponse,
    DataPlaneForwardOnlyRequest,
    DataPlaneForwardRequest,
    ForwardBackwardResponse,
    ForwardBackwardTaskRequest,
    ForwardOnlyRequest,
    ForwardRequest,
    ForwardResponse,
    GetTrainConfigsResponse,
    LoadRequest,
    LoadResponse,
    LrStepRequest,
    LrStepResponse,
    ModelResult,
    OkResponse,
    ResumeFromCheckpointRequest,
    SaveRequest,
    SaveResponse,
    SetLossRequest,
    SetLossResponse,
    SetLrSchedulerRequest,
    SetLrSchedulerResponse,
    SetOptimizerRequest,
    SetOptimizerResponse,
    SetProcessorRequest,
    SetProcessorResponse,
    SetTemplateRequest,
    SetTemplateResponse,
    StepRequest,
    StepResponse,
    TrainingProgressResponse,
    UploadToHubRequest,
    ZeroGradResponse,
)
from .processor import (
    ProcessorCallRequest,
    ProcessorCallResponse,
    ProcessorCreateRequest,
    ProcessorCreateResponse,
    ProcessorHeartbeatRequest,
    ProcessorHeartbeatResponse,
)
from .sampler import (
    SampledSequenceModel,
    SampleRequest,
    SampleResponseModel,
    SampleResponseModelList,
    SamplerAddAdapterRequest,
    SamplerAddAdapterResponse,
    SamplerCreateResponse,
    SamplerSetTemplateRequest,
    SamplerSetTemplateResponse,
)
from .server import (
    CheckpointPathResponse,
    DeleteCheckpointResponse,
    ErrorResponse,
    GetServerCapabilitiesResponse,
    HealthResponse,
    SupportedModel,
    WeightsInfoRequest,
    CapacityInfoResponse,
)
from .session import CreateSessionRequest, CreateSessionResponse, SessionHeartbeatRequest, SessionHeartbeatResponse
from .training import (
    Checkpoint,
    CheckpointsListResponse,
    CreateModelRequest,
    Cursor,
    LoraConfig,
    ParsedCheckpointTwinklePath,
    TrainingRun,
    TrainingRunsResponse,
    WeightsInfoResponse,
)

from .checkpoint import ResolvedLoadPath
from .base import (
    BACKEND_ONLY_KEY,
    DataModel,
    FieldRole,
    ResponseModel,
    StrictRequest,
    backend_kwarg,
    backend_only,
    fields_with_role,
    passthrough,
    read_backend_only,
    read_field_role,
)
from .data import (
    CORE_INPUT_KEYS,
    VLM_TENSOR_FIELDS,
    WireInputBatch,
    WireInputFeature,
    WireInputs,
    WireMessage,
    WireTrajectory,
    declared_wire_keys,
    export_batch,
)
from .lifecycle import CancelRequest, CancelResponse, RetrieveFutureRequest, TaskEnvelope, TaskStatus, TERMINAL_STATUSES
from .component import (
    DataAppendRequest,
    DataGetRequest,
    DataPlaneSampleRequest,
    DataPutRequest,
    DataRef,
    DataReleaseRequest,
    DataRowsResponse,
    UnloadAdapterPathsRequest,
)
