"""One-click: restart Ray cluster + launch Twinkle server + wait until ready.

Usage:
    python start_e2e_server.py                         # default config (transformers LoRA)
    python start_e2e_server.py --variant megatron-full-tp2pp2
    python start_e2e_server.py --variant full --set device_mesh.fsdp_size=2 --set device_mesh.dp_size=null
    python start_e2e_server.py --config my_config.yaml # fully custom config
    python start_e2e_server.py --kill-only             # just kill everything

Variants are generated from the two base configs by patching the model
application's ``args`` (see VARIANTS); ``--set key.path=value`` adds ad-hoc
overrides on top (value parsed as YAML; ``null`` deletes the key). The
generated file is written to tests/server/config/_generated_e2e.yaml.
"""
import argparse
import os
import signal
import subprocess
import sys
import time

import requests

# ── Paths ──
RAY = "/mnt/nas2/anaconda3/envs/tinker_myl/bin/ray"
PYTHON = "/mnt/nas2/anaconda3/envs/tinker_myl/bin/python"
WORKDIR = "/mnt/nas2/yunlin.myl/twinkle"
DEFAULT_CONFIG = "tests/server/config/server_config_4b_e2e.yaml"
RAY_TEMP_DIR = "/mnt/nas2/yunlin.myl/ray_logs"
SERVER_LOG = os.path.join(WORKDIR, "server_e2e.log")

# ── Config variants ──
# Each variant = (base config, {dotted path in model app args: value}).
# A value of None deletes the key (e.g. to swap device_mesh dimensions).
TRANSFORMERS_BASE = "tests/server/config/server_config_4b_e2e.yaml"
MEGATRON_BASE = "tests/server/config/server_config_4b_e2e_megatron.yaml"
_FULL = {
    "train_mode": "full",
    # Full-parameter training holds the deployment exclusively; use long
    # timeouts so the tenant is not expired mid-test.
    "adapter_config.adapter_timeout": 3600,
    "adapter_config.adapter_max_lifetime": 36000,
}
VARIANTS = {
    "lora": (TRANSFORMERS_BASE, {}),
    "full": (TRANSFORMERS_BASE, {**_FULL}),
    "full-fsdp2": (TRANSFORMERS_BASE, {**_FULL, "device_mesh.dp_size": None, "device_mesh.fsdp_size": 2}),
    "megatron-lora": (MEGATRON_BASE, {}),
    "megatron-full": (MEGATRON_BASE, {**_FULL}),
    "megatron-full-tp2pp2": (MEGATRON_BASE, {**_FULL, "device_mesh.dp_size": None, "device_mesh.tp_size": 2}),
    "megatron-full-tp2dp2": (MEGATRON_BASE, {**_FULL, "device_mesh.pp_size": None, "device_mesh.tp_size": 2}),
}
GENERATED_CONFIG = "tests/server/config/_generated_e2e.yaml"

# ── Server check ──
SERVER_URL = "http://localhost:9000/-/routes"
READY_KEYWORD = "processor"
TIMEOUT = 600
POLL_INTERVAL = 5


def build_config(base: str, overrides: dict, set_args: list[str]) -> str:
    """Generate a config from ``base`` by patching the model app's args.

    Returns the path (relative to WORKDIR) of the generated yaml.
    """
    import yaml

    with open(os.path.join(WORKDIR, base)) as f:
        cfg = yaml.safe_load(f)

    model_apps = [a for a in cfg["applications"] if a.get("import_path") == "model"]
    assert len(model_apps) == 1, f"expected exactly one model app in {base}"
    args = model_apps[0]["args"]

    merged = dict(overrides)
    for item in set_args:
        key, sep, raw = item.partition("=")
        assert sep, f"--set expects key.path=value, got: {item}"
        merged[key.strip()] = yaml.safe_load(raw)

    for dotted, value in merged.items():
        node = args
        *parents, leaf = dotted.split(".")
        for p in parents:
            node = node.setdefault(p, {})
        if value is None:
            node.pop(leaf, None)
        else:
            node[leaf] = value

    out_path = os.path.join(WORKDIR, GENERATED_CONFIG)
    with open(out_path, "w") as f:
        f.write("# AUTO-GENERATED by start_e2e_server.py — do not edit.\n")
        f.write(f"# base: {base}\n# model-args overrides: {merged}\n")
        yaml.safe_dump(cfg, f, sort_keys=False)
    print(f"    Generated config: {GENERATED_CONFIG} (base={base}, overrides={merged})")
    return GENERATED_CONFIG


def run(cmd, env=None, check=True):
    """Run a shell command, print it, and return CompletedProcess."""
    full_env = os.environ.copy()
    if env:
        full_env.update(env)
    print(f"  $ {cmd}")
    result = subprocess.run(cmd, shell=True, env=full_env,
                            capture_output=True, text=True)
    if result.returncode != 0 and check:
        print(f"    STDERR: {result.stderr.strip()}")
    return result


def kill_server():
    """Kill any existing twinkle.server processes."""
    print("[1/4] Killing existing Twinkle server processes...")
    result = subprocess.run(
        "ps aux | grep 'twinkle.server' | grep -v grep | awk '{print $2}'",
        shell=True, capture_output=True, text=True
    )
    pids = result.stdout.strip().split()
    for pid in pids:
        try:
            os.kill(int(pid), signal.SIGKILL)
            print(f"    Killed PID {pid}")
        except (ProcessLookupError, ValueError):
            pass
    if not pids:
        print("    No existing server found")
    time.sleep(2)


def restart_ray():
    """Stop and restart the Ray cluster (5 GPU + 1 CPU nodes)."""
    print("[2/4] Restarting Ray cluster...")
    run(f"{RAY} stop --force", check=False)
    time.sleep(2)

    # Head node: GPU 0,1,2,3 (4 GPUs for model PP=2 x DP=2)
    run(f"{RAY} start --head --port=6379 --num-gpus=4 "
        f"--disable-usage-stats --temp-dir={RAY_TEMP_DIR}",
        env={"CUDA_VISIBLE_DEVICES": "0,1,2,3"})

    # Worker: GPU 4 (1 GPU for sampler)
    run(f"{RAY} start --address=127.0.0.1:6379 --num-gpus=1",
        env={"CUDA_VISIBLE_DEVICES": "4"})

    # CPU-only worker (processor + server)
    run(f"{RAY} start --address=127.0.0.1:6379 --num-gpus=0",
        env={"CUDA_VISIBLE_DEVICES": ""})

    print("    Ray cluster started (4+1+0 GPUs)")


def launch_server(config: str):
    """Launch the Twinkle server in the background."""
    print(f"[3/4] Launching Twinkle server (config={config})...")
    config_path = os.path.join(WORKDIR, config)
    if not os.path.isfile(config_path):
        print(f"    ERROR: config not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    cmd = f"{PYTHON} -m twinkle.server launch --config {config_path}"
    log_fd = open(SERVER_LOG, "w")
    subprocess.Popen(
        cmd, shell=True, cwd=WORKDIR, stdout=log_fd, stderr=log_fd,
        env={**os.environ, "TWINKLE_TRUST_REMOTE_CODE": "1"},
        start_new_session=True,
    )
    print(f"    Server starting (log: {SERVER_LOG})")


def wait_ready():
    """Poll until the server is fully ready."""
    print(f"[4/4] Waiting for server to be ready (timeout={TIMEOUT}s)...")
    start = time.time()
    while time.time() - start < TIMEOUT:
        try:
            resp = requests.get(SERVER_URL, timeout=3)
            if resp.ok and READY_KEYWORD in resp.text:
                elapsed = time.time() - start
                print(f"    Server READY ({elapsed:.0f}s)")
                return True
        except (requests.ConnectionError, requests.Timeout):
            pass
        time.sleep(POLL_INTERVAL)

    print(f"    TIMEOUT: server not ready after {TIMEOUT}s", file=sys.stderr)
    print(f"    Check log: tail -50 {SERVER_LOG}", file=sys.stderr)
    return False


def main():
    parser = argparse.ArgumentParser(description="Restart Ray + launch Twinkle server")
    parser.add_argument("--config", default=None,
                        help=f"Server config yaml (overrides --variant; default: {DEFAULT_CONFIG})")
    parser.add_argument("--variant", default=None, choices=sorted(VARIANTS),
                        help="Named config variant generated from a base config (see VARIANTS)")
    parser.add_argument("--set", dest="set_args", action="append", default=[],
                        metavar="KEY.PATH=VALUE",
                        help="Extra model-args override, YAML-parsed (null deletes the key); repeatable")
    parser.add_argument("--kill-only", action="store_true",
                        help="Only kill server + Ray, don't restart")
    parser.add_argument("--no-ray", action="store_true",
                        help="Skip Ray restart (server only)")
    args = parser.parse_args()

    kill_server()

    if args.kill_only:
        run(f"{RAY} stop --force", check=False)
        print("Done (kill-only)")
        return 0

    if args.config:
        config = args.config
        if args.set_args:
            config = build_config(config, {}, args.set_args)
    else:
        base, overrides = VARIANTS[args.variant or "lora"]
        if args.variant or args.set_args:
            config = build_config(base, overrides, args.set_args)
        else:
            config = DEFAULT_CONFIG

    if not args.no_ray:
        restart_ray()

    launch_server(config)

    if wait_ready():
        print("\n✓ All set. Run your test:")
        print(f"  TWINKLE_TEST_GPU_E2E=1 {PYTHON} -u tests/server/integration/test_full_cycle_e2e.py")
        return 0
    else:
        return 1


if __name__ == "__main__":
    sys.exit(main())
