# Copyright (c) ModelScope Contributors. All rights reserved.
"""Training-domain descriptors for native-TQ async multi-LoRA RL."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, TypedDict


@dataclass(frozen=True)
class LoraContext:
    tenant_id: str
    training_run_id: str
    base_model_id: str
    adapter_name: str
    tool_profile: str = 'default'

    @property
    def key(self) -> str:
        return f'{self.tenant_id}/{self.training_run_id}/{self.adapter_name}'

    def partition_id(self, step: int) -> str:
        return f'{self.key}/train_{step}'


@dataclass(frozen=True)
class RolloutPolicy:
    """The immutable policy snapshot used by one rollout group."""

    context_key: str
    adapter_name: str
    version: int
    adapter_path: str | None


@dataclass(frozen=True)
class PartitionAdmission:
    """Control-plane admission result for one complete training-data partition.

    A partition is only a training-data batch. Its prompt groups may be
    generated by different policy snapshots.
    """

    context: LoraContext
    partition_id: str
    step: int
    target_groups: int
    num_generations: int
    created_order: int

    @property
    def sample_count(self) -> int:
        return self.target_groups * self.num_generations


@dataclass
class PromptGroup:
    """A prompt and the BatchMeta descriptor reserved for its generated samples."""

    context: LoraContext
    partition: PartitionAdmission
    group_id: str
    prompt: dict[str, Any]
    batch_meta: Any

    @property
    def partition_id(self) -> str:
        return self.partition.partition_id

    @property
    def num_samples(self) -> int:
        return self.partition.num_generations


@dataclass
class PreparedPartition:
    """Partition prepared in TQ and ready for sampler submission."""

    admission: PartitionAdmission
    groups: tuple[PromptGroup, ...]
    sampling_params: Any


@dataclass
class ClaimedBatch:
    """A TQ-consumed batch and the BatchMeta descriptor selecting its samples."""

    admission: PartitionAdmission
    data: Any
    batch_meta: Any
    sample_tags: tuple[dict[str, Any], ...] = ()


class RolloutOutput(TypedDict, total=False):
    logprobs: list[float]
    rewards: float
    completion_length: int
    generation_idx: int
    rollout_policy_version: int
    rollout_adapter_path: str | None
    rollout_policy_versions: list[int]
    initial_policy_version: int
    final_policy_version: int
    policy_version_span: int
